name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pytest:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v3
      - name: Install dev dependencies
        run: pdm install --dev
      - name: Run tests
        run: pdm run pytest
